apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
      - Github:
        - abbr: GH
          href: https://github.com/

  services.yaml: |
    - My First Group:
        - My First Service:
            href: https://google.com/
            description: Homepage is awesome
        - My test Service:
            href: https://google.com/
            description: Homepage is awesome
    - My secondGroup:
        - My second Service:
            href: https://github.com/
            description: Homepage is awesome

  widgets.yaml: |
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - resources:
            backend: resources
            expanded: true
            cpu: true
            memory: true
            network: default
        - search:
            provider: duckduckgo
            target: _blank
  docker.yaml: ""
